CREATE TABLE todos
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(50)                             NOT NULL,
    description VARCHAR(500),
    completed   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_todos PRIMARY KEY (id)
);
